### ISSUE TITLE
MS Graph subscription not working

### ISSUE THREAD

**Issue by vishnuvg1984** [microsoftgraph/microsoft-graph-explorer-api#126]
I tried to create a MS Graph Mail Subscription through Graph Explorer as given below . This was working fine till 1 week back perfectly.

{

"changeType": "created",
"notificationUrl": "https://glowhookfunction.azurewebsites.net/api/ProcessMail",
"resource": "me/mailFolders('Inbox')/messages",
"expirationDateTime":"2019-10-09T18:23:45.9356913Z"
}

and I getting the error 

{
    "error": {
        "code": "ExtensionError",
        "message": "Operation: Create; Exception: [Status Code: InternalServerError; Reason: Request has been quarantined by condition.]",
        "innerError": {
            "request-id": "65ee6fd6-dd28-4348-bead-c3316c1ea1fb",
            "date": "2019-10-07T11:09:05"
        }
    }
}

This was working fine till last week. The notification is sending to an Azure function. I validating the "validationToken" and sends it back as well.  I tried to create a few community posts, but less response, Any idea

**Comment by andrueastman** [comment]
@vishnuvg1984 
Thanks for reaching out. 
Could you please put up this question on StackOverflow with the tags "microsoft-graph"? 
This way it will be much easier to get someone on the relevant team to help out asap.
