### ISSUE TITLE
Investigate if "unconsenting"  a permission is possible with MSAL

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-api#157]
It would be great for users to revoke consent to already consented permissions. This investigation will help us give this experience to our users. This is a requested feature from a customer here: https://github.com/microsoftgraph/microsoft-graph-explorer/issues/367

**Comment by darrelmiller** [comment]
No it is not possible.  The only solution is to completely delete the Service Prinicipal which will reset all consents.
