### ISSUE TITLE
Add Accept-Language support for Samples and CapabilitiesAPI/PermissionsAPI

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-api#198]
The DevX API should return descriptive content that respects the requested language.

[AB#4592](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/4592)

**Comment by ddyett** [comment]
Part of AB#4592
