### ISSUE TITLE
Move samples queries file into blob storage

### ISSUE THREAD

**Issue by irvinesunday** [microsoftgraph/microsoft-graph-explorer-api#204]
The _SamplesQueries.json_ file is currently stored in a folder directory. The problem with this is:
- Updating the web app will overwrite any changes made to the _SamplesQueries.json_
- If we decide to scale out, we will have two copies of the file.
- We need to support localization of these resources, so some refactoring/normalization of this data is needed.

This file needs to be moved to an Azure blob storage.

[AB#4592](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/4592)

**Comment by ddyett** [comment]
Part of AB#4592
