### ISSUE TITLE
Ensure OpenAPI description contains delete operations for contained collections

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-api#217]
We believe this is an issue with OpenAPI.Net.Odata  Related to #191 

[AB#4775](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/4775)

**Comment by irvinesunday** [comment]
Tracked with this issue: https://github.com/microsoft/OpenAPI.NET.OData/issues/59
