### ISSUE TITLE
Always ensure generated modules have cmdlets in them

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/microsoft-graph-explorer-api#246]
Since this SDK is built on a `beta` API, changes are made to the service on a daily. We need to ensure that when we generate modules, we check to see if their `OpenAPI` docs have paths in them. This results in modules with no cmdlets [Teams.Channel](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/openApiDocs/beta/Teams.Channel.yml).

[AB#4724](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/4724)

**Comment by darrelmiller** [comment]
If the OpenAPIDocument has no paths we should return a 400 error from the service to indicate that that the query parameters were not good.  This will allow the PowerShell generation to not create a module for this.
