### ISSUE TITLE
Pick Permissions list directly from Service principal and update weekly.

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-api#256]
We now have the Select Permissions option on Graph Explorer that allows users to select the permissions they want and consent to them.

DevX should be able to get information to update/feed this document with the list of permissions and descriptions directly from the service principal using tihis call.

More to this, it should schedule a weekly update of these permissions to ensure we have the most upto date copy of the permissions. 

This weekly update should also update the permissions document that we get from Jackson's tool. 
[AB#7017](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7017)

**Comment by irvinesunday** [comment]
Completed
