### ISSUE TITLE
An Incompatible types error is reported in the sample code.

### ISSUE THREAD

**Issue by real-liyongsheng** [microsoftgraph/microsoft-graph-explorer-api#341]
An Incompatible types error is reported in the sample code.
How to use the ConversationMemberCollectionPage ?
`channel.members = membersList;`
Required: com.microsoft.graph.requests.extensions.ConversationMemberCollectionPage
Found: java.util.LinkedList

https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=java

```
IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

Channel channel = new Channel();
channel.membershipType = ChannelMembershipType.PRIVATE;
channel.displayName = "My First Private Channel";
channel.description = "This is my first private channels";
LinkedList<ConversationMember> membersList = new LinkedList<ConversationMember>();
AadUserConversationMember members = new AadUserConversationMember();
members.additionalDataManager().put("user@odata.bind", new JsonPrimitive("https://graph.microsoft.com/v1.0/users('{user_id}')"));
LinkedList<String> rolesList = new LinkedList<String>();
rolesList.add("owner");
members.roles = rolesList;
membersList.add(members);
channel.members = membersList;

graphClient.teams("{group_id}").channels()
	.buildRequest()
	.post(channel);
```

**Comment by baywet** [comment]
Hi @real-liyongsheng 
Thanks for reporting this issue with java snippets.
I have transferred your issue to the repository that contains the snippets generation code.
the snippet should be something among these lines
```Java
IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

Channel channel = new Channel();
channel.membershipType = ChannelMembershipType.PRIVATE;
channel.displayName = "My First Private Channel";
channel.description = "This is my first private channels";
LinkedList<ConversationMember> membersList = new LinkedList<ConversationMember>();
AadUserConversationMember members = new AadUserConversationMember();
members.additionalDataManager().put("user@odata.bind", new JsonPrimitive("https://graph.microsoft.com/v1.0/users('{user_id}')"));
LinkedList<String> rolesList = new LinkedList<String>();
rolesList.add("owner");
members.roles = rolesList;
membersList.add(members);
channel.members = new ConversationMemberCollectionPage(membersList, null);

graphClient.teams("{group_id}").channels()
	.buildRequest()
	.post(channel);
```

**Comment by real-liyongsheng** [comment]
> Hi @real-liyongsheng
> Thanks for reporting this issue with java snippets.
> I have transferred your issue to the repository that contains the snippets generation code.
> the snippet should be something among these lines
> 
> ```java
> IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();
> 
> Channel channel = new Channel();
> channel.membershipType = ChannelMembershipType.PRIVATE;
> channel.displayName = "My First Private Channel";
> channel.description = "This is my first private channels";
> LinkedList<ConversationMember> membersList = new LinkedList<ConversationMember>();
> AadUserConversationMember members = new AadUserConversationMember();
> members.additionalDataManager().put("user@odata.bind", new JsonPrimitive("https://graph.microsoft.com/v1.0/users('{user_id}')"));
> LinkedList<String> rolesList = new LinkedList<String>();
> rolesList.add("owner");
> members.roles = rolesList;
> membersList.add(members);
> channel.members = new ConversationMemberCollectionPage(membersList, null);
> 
> graphClient.teams("{group_id}").channels()
> 	.buildRequest()
> 	.post(channel);
> ```

Thank you for your answer. but there is a  wrong:
 ConversationMemberCollectionPage
(com.microsoft.graph.requests.extensions.ConversationMemberCollectionResponse,
IConversationMemberCollectionRequestBuilder)
in ConversationMemberCollectionPage cannot be applied
to
(java.util.LinkedList<com.microsoft.graph.models.extensions.ConversationMember>,
null)
`new ConversationMemberCollectionPage(membersList, null);`

**Comment by baywet** [comment]
right, sorry I forgot a step:
```Java
IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

Channel channel = new Channel();
channel.membershipType = ChannelMembershipType.PRIVATE;
channel.displayName = "My First Private Channel";
channel.description = "This is my first private channels";
AadUserConversationMember members = new AadUserConversationMember();
members.additionalDataManager().put("user@odata.bind", new JsonPrimitive("https://graph.microsoft.com/v1.0/users('{user_id}')"));
LinkedList<String> rolesList = new LinkedList<String>();
rolesList.add("owner");
members.roles = rolesList;
final ConversationMemberCollectionResponse response = new ConversationMemberCollectionResponse();
response.value = new LinkedList<ConversationMember>();
response.value.add(members);
channel.members = new ConversationMemberCollectionPage(response, null);
graphClient.teams("{group_id}").channels()
	.buildRequest()
	.post(channel);
```
