### ISSUE TITLE
Change sample code title to "SDK Sample Code"

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-api#35]
Currently the samples show as:

![image](https://user-images.githubusercontent.com/447694/56611254-56ce8c00-65df-11e9-8dc9-be17c4e20c2d.png)

Please change the title to "SDK Sample Code" instead of just "Sample Code"

**Comment by andrueastman** [comment]
Title updated and can be previewed [here](https://review.docs.microsoft.com/en-us/graph/api/plannerbucket-delete?moniker=graph-rest-1.0&branch=andrueastman%2Fsnippets-preview-get-post-js-csharp&view=graph-rest-1.0&tabs=CS#sdk-sample-code)
