### ISSUE TITLE
Add suppression for failures due to snippets import to ensure PR passes

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-api#37]
Currently this PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/4276 is failing due to APIDoctor checks.  In order to ensure that we can get the PR out on Friday, we should suppress this error.

/cc @jthake-msft

**Comment by andrueastman** [comment]
PR now passes all checks https://github.com/microsoftgraph/microsoft-graph-docs/pull/4276
@darrelmiller @jthake-msft
