### ISSUE TITLE
Some pages don't get snippets. 

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-api#38]
Why does this page, or any of the "tabs" related functions not get snippets injected?
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-
reference/v1.0/api/teamstab-list.md

https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-1.0&branch=andrueastman%2Fsnippets-preview-get-post-js-csharp

**Comment by andrueastman** [comment]
This is due to the header annotations of the requests in the raw markdown marking the requests as "ignored" requests. 

Once this is changed, the snippets should present.
