### ISSUE TITLE
When I call the API to get message list by using delta query , I report the error of  bad request. how to solve it?

### ISSUE THREAD

**Issue by real-liyongsheng** [microsoftgraph/microsoft-graph-explorer-api#391]
When I call the API to get message list by using delta query , I report the error of  bad request. how to solve it?
`/teams/{id}/channels/{id}/messages/delta?$filter=lastModifiedDateTime gt 2019-02-27T07:13:28.000z`
https://docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&tabs=http

**Comment by MIchaelMainer** [comment]
Can you post your question to https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-mail.html and provide a link in this issue? This repo is specifically for the Graph Explorer API.
