### ISSUE TITLE
[GraphAPI Beta] - Custodians id returned without dashes

### ISSUE THREAD

**Issue by MichaMican** [microsoftgraph/microsoft-graph-explorer-api#392]
When using the Beta custodian endpoint described by the [docs](https://docs.microsoft.com/de-de/graph/api/ediscoverycase-list-custodians?view=graph-rest-beta&tabs=http ) I realised that the returned (Object) Id is returned without dashes ("-"). This is inconsistent with the id usage everywhere else in the Graph API, as the id is returned there with the dashes. 
[AB#7005](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7005)

**Comment by ddyett** [comment]
Please post this question to Microsoft Q&A as it's not specific to this particular service.
