### ISSUE TITLE
OpenAPI doc has PATCH instead of PUT for /authentication/phoneMethods

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/microsoft-graph-explorer-api#408]
The [OpenAPI doc](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/openApiDocs/beta/Identity.SignIns.yml#L11358) wrongly describes  `/users/{user-id}/authentication/phoneMethods/{phoneAuthenticationMethod-id}` as a PATCH request instead of PUT. See https://docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&tabs=http.
#### Current
``` yaml
 '/users/{user-id}/authentication/phoneMethods/{phoneAuthenticationMethod-id}':
    patch:
      tags:
        - users.authentication
      summary: Update the navigation property phoneMethods in users
      operationId: users.authentication_UpdatePhoneMethods
     ....
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
```

#### Expected
``` yaml
 '/users/{user-id}/authentication/phoneMethods/{phoneAuthenticationMethod-id}':
    put:
      tags:
        - users.authentication
      summary: Update the navigation property phoneMethods in users
      operationId: users.authentication_UpdatePhoneMethods
     ....
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
```

Related to https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/278 
[AB#7007](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7007)

**Comment by darrelmiller** [comment]
The workload team are going to be fixing their API to support PATCH.  OData requires PATCH support.  PUT is optional.
