### ISSUE TITLE
How can I send a checksum for an upload to verify the file integrity for a file transfer.

### ISSUE THREAD

**Issue by butonic** [microsoftgraph/microsoft-graph-explorer-api#418]
I tried finding related pages in the v1.0 and beta docs and this issue tracker. Is it possible to send a special checksum header along with a file upload to give the server side the chance to verify the bytes have been transferred correctly?

Or is there a reason why this is considered unnecessary? TCP only ensures a weak CRC. Does HTTPS help with this? 
[AB#7628](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7628)

Related:
- [driveItem resource type - Properties: file](https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0#properties)
- [File resource type - Properties: hashes](https://docs.microsoft.com/en-us/graph/api/resources/file?view=graph-rest-1.0#properties)
- [Hashes resource type](https://docs.microsoft.com/en-us/graph/api/resources/hashes?view=graph-rest-1.0)

**Comment by darrelmiller** [comment]
Questions about how use Microsoft Graph are best directed to Microsoft Q&A https://docs.microsoft.com/en-us/answers/products/
