### ISSUE TITLE
Filtering messages with plus email address

### ISSUE THREAD

**Issue by ShrujanKotturi** [microsoftgraph/microsoft-graph-explorer-api#422]
With the addition of plus addressing for office 365 emails - https://techcommunity.microsoft.com/t5/exchange/support-for-plus-addressing-in-office-365/m-p/1170418, we would like to filter messages with email address with plus in them like - https://graph.microsoft.com/v1.0/me/messages?$search="to:jane+doe@office.com" 
[AB#7672](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7672)

**Comment by MIchaelMainer** [comment]
Thank you for opening this issue. This appears to be a a feature request. Please use the [Microsoft Graph User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests) to search for existing feature requests, and to open new feature requests. Provide a link to your feature request in this issue.
