### ISSUE TITLE
Ability to filter users with assignedPlans

### ISSUE THREAD

**Issue by azb96** [microsoftgraph/microsoft-graph-explorer-api#431]
A query filter for querying users according to their servicePlanId's on assignedPlans collection should be added. 
For example a query for getting users with  4828c8ec-dc2e-4779-b502-87ac9ce28ab7 (Phone System) servicePlanId : https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24select%3Did%2CdisplayName%2CassignedPlans&method=GET&version=beta&GraphUrl=https://graph.microsoft.com 

 
[AB#7812](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7812)

**Comment by darrelmiller** [comment]
Microsoft Q&A  is the best place to ask questions about features of Microsoft Graph https://docs.microsoft.com/en-us/answers/products/
