### ISSUE TITLE
Code fence for CSharp is not displaying correctly

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-api#44]
I believe the code fence should be csharp and not cs.
![image](https://user-images.githubusercontent.com/447694/57670434-48bbcc00-75dd-11e9-8bf0-4b3785c14b4c.png)

**Comment by andrueastman** [comment]
Thanks for pointing this out. This should be resolved once this [PR ](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4614)goes through.
