### ISSUE TITLE
Generate Expand expression

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-api#8]

**Comment by titusgicheru** [comment]
The graph SDK has a method SelectAndExpand() - The logic in the SnippetsGenerator currently supports $select query option and not expand. The implementation here needs further investigation.

Scenarios for $expand
GET /v1.0/me/drive/root?$expand=children($select=id,name) HTTP/1.1
GET /v1.0/users?$expand=directReports HTTP/1.1

**Comment by andrueastman** [comment]
Resolved under #30
