### ISSUE TITLE
Parameter sorting in functions not always correct 

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/microsoft-graph-explorer-api#87]
Looking at the snippet below, found [here](https://docs.microsoft.com/en-us/graph/api/tablecollection-add?view=graph-rest-1.0&tabs=csharp#request)

```
GraphServiceClient graphClient = new GraphServiceClient( authProvider );
var address = "Sheet1!A1:D5";
var hasHeaders = true;
await graphClient.Me.Drive.Items["{id}"].Workbook.Tables
	.Add(address,hasHeaders)
	.Request()
	.PostAsync();
```

The parameters for the `Add` function are in the wrong order. and should be called as so 
```
.Add(hasHeaders,address)
```

Also, the nullability of the parameters should be handled if appropiate.

**Comment by MIchaelMainer** [comment]
Parameter order from metadata must be maintained. This has been a source of breaking changes in the past for the SDK.

**Comment by andrueastman** [comment]
The snippet generator already enforces following the order of the metadata as shown below. 
![image](https://user-images.githubusercontent.com/6464005/63322866-1c76c080-c32d-11e9-96a3-3b4dc5f179b8.png)

However, the SDK has the implements the parameters in the reverse order causing the build failure. You can see that [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/4186d848cabfd93263c1d9a42ae3473dd0560282/src/Microsoft.Graph/Requests/Generated/IWorkbookTablesCollectionRequestBuilder.cs#L43)

@MIchaelMainer Does it make sense to file an issue with the sdk generator then?

**Comment by MIchaelMainer** [comment]
The code generator implementation shouldn't have done that. It is now baked into a couple of years of generated libraries so we can't change that without breaking customers. We can't break customers with this so we will need to keep the SDK generator the same, and the snippet generator will need to (unfortunately) respect that.

**Comment by andrueastman** [comment]
Taking a look at the SDK generator code [here](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/29d268b7fb11ca4dcfe53c0f71f84be023f6b08e/Templates/CSharp/Base/IRequestBuilder.Base.template.tt#L110), the method used is that the parameters are ordered first by the required parameters then by the optional parameters (which now makes sense for this case).

The resolution should therefore be in that fashion. :smile:
